### ISSUE TITLE
Bug Report for score-of-a-string

### ISSUE THREAD

**Issue by TannerLow** [neetcode-gh/leetcode#4718]
Bug Report for https://neetcode.io/problems/score-of-a-string

Please describe the bug below and include any steps to reproduce the bug or screenshots if possible.

Running the code does nothing and my submission status is listed as "Unknown"

**Comment by Srihari2222** [comment]
The issue has been resolved. If you further face any issue, please attach images for clarity.

**Comment by TannerLow** [comment]
It has not been fixed and the same error still exists. I am using Google Chrome Version 139.0.7258.139 (Official Build) (64-bit)

<img width="1463" height="822" alt="Image" src="https://github.com/user-attachments/assets/6fb439ba-ecea-435b-86e4-f7f530110b94" />

**Comment by Srihari2222** [comment]
Thanks for the image. I fixed a bug in the backend. Will soon reflect on the site.
